name: Build iOS 6 IPA

on:
  workflow_dispatch:

jobs:
  build-ios6-compat:
    name: Build iOS 6 IPA
    runs-on: macos-13
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: true
          fetch-depth: 0

      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '14.1.0'

      - name: Fix Project Format (Minimal Change)
        run: |
          # Only fix the objectVersion which is needed for the project to open
          sed -i '' 's/objectVersion = 77/objectVersion = 56/' xc/CrazyCattle3D.xcodeproj/project.pbxproj
          sed -i '' 's/preferredProjectObjectVersion = 77/preferredProjectObjectVersion = 56/' xc/CrazyCattle3D.xcodeproj/project.pbxproj

      - name: Build with Default Settings
        run: |
          xcodebuild clean archive \
            -project xc/CrazyCattle3D.xcodeproj \
            -scheme "CrazyCattle3D" \
            -configuration Release \
            -archivePath build/CrazyCattle3D.xcarchive \
            -sdk iphoneos \
            -destination 'generic/platform=iOS' \
            ONLY_ACTIVE_ARCH=NO \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO \
            SWIFT_OPTIMIZATION_LEVEL="-Onone"

      - name: Create Initial IPA
        run: |
          cp -R build/CrazyCattle3D.xcarchive/Products/Applications/CrazyCattle3D.app .
          mkdir -p Payload
          cp -R CrazyCattle3D.app Payload/
          zip -r CrazyCattle3D-initial.ipa Payload
          rm -rf Payload CrazyCattle3D.app

      - name: Install tools
        run: |
          brew install unzip
          pip3 install biplist

      - name: Process IPA for iOS 6 Compatibility
        run: |
          mkdir -p ios6-compat
          cd ios6-compat
          
          # Extract the IPA
          unzip -q ../CrazyCattle3D-initial.ipa
          
          # Find the .app directory
          APP_DIR=$(find Payload -name "*.app" -type d | head -1)
          if [ -z "$APP_DIR" ]; then
            echo "ERROR: No .app directory found"
            exit 1
          fi
          
          echo "App directory: $APP_DIR"
          
          # Modify Info.plist for iOS 6
          if [ -f "$APP_DIR/Info.plist" ]; then
            echo "Backing up original Info.plist"
            cp "$APP_DIR/Info.plist" "$APP_DIR/Info.plist.bak"
            
            echo "Modifying Info.plist for iOS 6 compatibility"
            
            # Convert to XML for easier editing
            plutil -convert xml1 "$APP_DIR/Info.plist"
            
            # Read the current MinimumOSVersion
            CURRENT_MIN_OS=$(plutil -extract MinimumOSVersion raw "$APP_DIR/Info.plist" 2>/dev/null || echo "Unknown")
            echo "Current MinimumOSVersion: $CURRENT_MIN_OS"
            
            # Set MinimumOSVersion to 6.0
            plutil -replace MinimumOSVersion -string "6.0" "$APP_DIR/Info.plist"
            
            # Set UIRequiredDeviceCapabilities for older devices 
            plutil -replace UIRequiredDeviceCapabilities -xml "<array><string>armv7</string></array>" "$APP_DIR/Info.plist" || true
            
            # Remove potentially problematic keys
            plutil -remove UIApplicationSceneManifest "$APP_DIR/Info.plist" || true
            plutil -remove NSUserActivityTypes "$APP_DIR/Info.plist" || true
            
            # Add iOS 6 compatibility keys
            plutil -replace UIDeviceFamily -xml "<array><integer>1</integer><integer>2</integer></array>" "$APP_DIR/Info.plist" || true
            plutil -replace LSRequiresIPhoneOS -bool YES "$APP_DIR/Info.plist" || true
            
            echo "Info.plist modified for iOS 6 compatibility"
          else
            echo "ERROR: Info.plist not found"
            exit 1
          fi
          
          # Remove any problematic files
          echo "Cleaning up potentially problematic files"
          find Payload -name ".DS_Store" -delete
          find Payload -name "ftm.dylib" -delete
          
          # Set necessary permissions
          echo "Setting executable permissions"
          EXECUTABLE_NAME=$(plutil -extract CFBundleExecutable raw "$APP_DIR/Info.plist" 2>/dev/null)
          if [ -n "$EXECUTABLE_NAME" ] && [ -f "$APP_DIR/$EXECUTABLE_NAME" ]; then
            chmod +x "$APP_DIR/$EXECUTABLE_NAME"
            echo "Set executable permissions for $EXECUTABLE_NAME"
          fi
          
          # Create the iOS 6 compatible IPA
          cd ..
          rm -rf CrazyCattle3D-iOS6.ipa
          cd ios6-compat
          echo "Creating iOS 6 compatible IPA"
          zip -qr ../CrazyCattle3D-iOS6.ipa Payload
          cd ..
          
          echo "Finished creating iOS 6 compatible IPA"
          ls -la CrazyCattle3D-iOS6.ipa

      - name: Create Alternative IPA with Minimal Info.plist
        run: |
          mkdir -p ios6-minimal
          cd ios6-minimal
          
          # Extract the IPA again
          unzip -q ../CrazyCattle3D-initial.ipa
          
          # Find the .app directory
          APP_DIR=$(find Payload -name "*.app" -type d | head -1)
          if [ -z "$APP_DIR" ]; then
            echo "ERROR: No .app directory found"
            exit 1
          fi
          
          # Get essential info from the original Info.plist
          EXECUTABLE_NAME=$(plutil -extract CFBundleExecutable raw "$APP_DIR/Info.plist" 2>/dev/null || echo "CrazyCattle3D")
          BUNDLE_ID=$(plutil -extract CFBundleIdentifier raw "$APP_DIR/Info.plist" 2>/dev/null || echo "com.yourcompany.CrazyCattle3D")
          BUNDLE_NAME=$(plutil -extract CFBundleName raw "$APP_DIR/Info.plist" 2>/dev/null || echo "CrazyCattle3D")
          BUNDLE_VERSION=$(plutil -extract CFBundleVersion raw "$APP_DIR/Info.plist" 2>/dev/null || echo "1.0")
          SHORT_VERSION=$(plutil -extract CFBundleShortVersionString raw "$APP_DIR/Info.plist" 2>/dev/null || echo "1.0")
          
          # Create a minimal Info.plist
          echo "Creating minimal Info.plist"
          cat > "$APP_DIR/Info.plist" << EOF
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
          <key>CFBundleExecutable</key>
          <string>$EXECUTABLE_NAME</string>
          <key>CFBundleIdentifier</key>
          <string>$BUNDLE_ID</string>
          <key>CFBundleName</key>
          <string>$BUNDLE_NAME</string>
          <key>CFBundleVersion</key>
          <string>$BUNDLE_VERSION</string>
          <key>CFBundleShortVersionString</key>
          <string>$SHORT_VERSION</string>
          <key>MinimumOSVersion</key>
          <string>6.0</string>
          <key>UIDeviceFamily</key>
          <array>
          <integer>1</integer>
          <integer>2</integer>
          </array>
          <key>UIRequiredDeviceCapabilities</key>
          <array>
          <string>armv7</string>
          </array>
          <key>LSRequiresIPhoneOS</key>
          <true/>
          </dict>
          </plist>
          EOF
          
          # Set executable permissions
          if [ -f "$APP_DIR/$EXECUTABLE_NAME" ]; then
            chmod +x "$APP_DIR/$EXECUTABLE_NAME"
          fi
          
          # Clean up problematic files
          find Payload -name ".DS_Store" -delete
          find Payload -name "ftm.dylib" -delete
          
          # Create the minimal IPA
          cd ..
          rm -rf CrazyCattle3D-iOS6-minimal.ipa
          cd ios6-minimal
          echo "Creating iOS 6 minimal IPA"
          zip -qr ../CrazyCattle3D-iOS6-minimal.ipa Payload
          cd ..
          
          echo "Finished creating iOS 6 minimal IPA"
          ls -la CrazyCattle3D-iOS6-minimal.ipa

      - name: Upload Standard IPA
        uses: actions/upload-artifact@v4
        with:
          name: CrazyCattle3D-iOS6
          path: CrazyCattle3D-iOS6.ipa
          retention-days: 90
          
      - name: Upload Minimal IPA
        uses: actions/upload-artifact@v4
        with:
          name: CrazyCattle3D-iOS6-minimal
          path: CrazyCattle3D-iOS6-minimal.ipa
          retention-days: 90
