name: Build iOS 6 Compatible IPA

on:
  workflow_dispatch:
    inputs:
      ios_version:
        description: 'iOS version to target'
        required: true
        default: '6.0'
        type: string

jobs:
  build-ios6:
    name: Build iOS 6 IPA
    runs-on: macos-13
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: true
          fetch-depth: 0

      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '5.1.1'

      - name: Fix Project Format
        run: |
          sed -i '' 's/objectVersion = 77/objectVersion = 56/' xc/CrazyCattle3D.xcodeproj/project.pbxproj
          sed -i '' 's/preferredProjectObjectVersion = 77/preferredProjectObjectVersion = 56/' xc/CrazyCattle3D.xcodeproj/project.pbxproj

      - name: List Available SDKs
        run: xcodebuild -showsdks

      - name: Archive Build (Unsigned) for iOS 6
        run: |
          xcodebuild clean archive \
            -project xc/CrazyCattle3D.xcodeproj \
            -scheme "CrazyCattle3D" \
            -configuration Release \
            -archivePath build/CrazyCattle3D.xcarchive \
            -sdk iphoneos \
            -destination 'generic/platform=iOS' \
            ONLY_ACTIVE_ARCH=NO \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO \
            SWIFT_OPTIMIZATION_LEVEL="-Onone" \
            IPHONEOS_DEPLOYMENT_TARGET=${{ github.event.inputs.ios_version }} \
            ARCHS="armv7 armv7s" \
            VALID_ARCHS="armv7 armv7s" \
            OTHER_CFLAGS="-miphoneos-version-min=${{ github.event.inputs.ios_version }}" \
            OTHER_LDFLAGS="-miphoneos-version-min=${{ github.event.inputs.ios_version }}"

      - name: Create IPA from Archive
        run: |
          cp -R build/CrazyCattle3D.xcarchive/Products/Applications/CrazyCattle3D.app .
          mkdir -p Payload
          cp -R CrazyCattle3D.app Payload/
          zip -r CrazyCattle3D-iOS6.ipa Payload
          rm -rf Payload CrazyCattle3D.app

      - name: Upload iOS 6 Artifact
        uses: actions/upload-artifact@v4
        with:
          name: CrazyCattle3D-iOS6.ipa
          path: CrazyCattle3D-iOS6.ipa
          retention-days: 90
